#!/usr/bin/env bash
# Quick deploy script for Render.com

echo "🚀 Deploying Vedic Astro Backend to Render.com"
echo ""
echo "Prerequisites:"
echo "  ✓ GitHub repository with your code"
echo "  ✓ Render.com account (free tier available)"
echo ""
echo "Steps:"
echo ""
echo "1️⃣  Push your code to GitHub:"
echo "    git add ."
echo "    git commit -m 'Deploy backend'"
echo "    git push origin main"
echo ""
echo "2️⃣  Create Web Service in Render:"
echo "    • Go to: https://render.com/new"
echo "    • Select 'Web Service'"
echo "    • Connect your GitHub repo"
echo "    • Root Directory: backend"
echo "    • Build Command: pip install -r requirements.txt"
echo "    • Start Command: PYTHONPATH=/opt/render/project/src uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "3️⃣  Add Environment Variables in Render:"
echo "    Copy these from backend/.env and add to Render dashboard:"
echo "      - MONGODB_URL"
echo "      - MONGODB_DB_NAME"
echo "      - JWT_SECRET"
echo "      - TWILIO_ACCOUNT_SID"
echo "      - TWILIO_AUTH_TOKEN"
echo "      - Plus: PYTHONPATH=/opt/render/project/src"
echo ""
echo "🔐 IMPORTANT: Whitelist Render IPs in MongoDB Atlas:"
echo "    Go to MongoDB Atlas → Network Access → Add IP Address"
echo "    Add these IP ranges:"
echo "      • 74.220.48.0/24 (Render Backend - Range 1)"
echo "      • 74.220.56.0/24 (Render Backend - Range 2)"
echo "    See MONGODB_WHITELIST.md for detailed steps"
echo ""
echo "4️⃣  Update Vercel Frontend:"
echo "    • Go to: https://vercel.com/your-project/settings/environment-variables"
echo "    • Add: NEXT_PUBLIC_BACKEND_URL = https://your-app.onrender.com"
echo "    • Redeploy frontend"
echo ""
echo "5️⃣  Test your deployment:"
echo "    curl https://your-app.onrender.com/health"
echo ""
echo "📚 Full guide: See DEPLOYMENT.md for detailed instructions"
